# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180614_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Doing',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Done',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='ToDo',
        ),
    ]
